# Generated by Django 5.1 on 2025-07-23 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of participants allowed'),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
