# Generated by Django 5.1 on 2025-07-23 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_learningpath_progress_remove_module_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
