# Generated by Django 5.2.4 on 2025-07-24 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_quizattempt_quizsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='quiz',
        ),
        migrations.AddField(
            model_name='badge',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.module'),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.quizattempt'),
        ),
    ]
