# Generated by Django 5.2.4 on 2025-07-24 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_quizresponse_quiz_badge_module_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Competencies'},
        ),
        migrations.AlterModelOptions(
            name='quizsettings',
            options={'verbose_name_plural': 'Quiz Settings'},
        ),
        migrations.AlterModelOptions(
            name='usercompetency',
            options={'verbose_name_plural': 'User Competencies'},
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='competency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='shuffle_answers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercompetency',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercompetency',
            name='best_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usercompetency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badge_icons/'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hackathonsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='hackathon_submissions/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.competency'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='myapp.competency'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Stores quiz settings snapshot'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timed_out', 'Timed Out')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken',
            field=models.FloatField(blank=True, help_text='Time taken in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.answer'),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.question'),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='response_time',
            field=models.FloatField(help_text='Response time in seconds'),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='competency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='myapp.competency'),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum attempts per day'),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, help_text='Minimum score to pass', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='question_count',
            field=models.PositiveIntegerField(default=10, help_text='Number of questions per quiz', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='quizsettings',
            name='time_limit',
            field=models.PositiveIntegerField(default=10, help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='usercompetency',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_competencies', to='myapp.competency'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'is_correct'], name='myapp_answe_questio_59c4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['user', 'timestamp'], name='myapp_asses_user_id_996589_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['user', 'date_awarded'], name='myapp_badge_user_id_3172fc_idx'),
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=models.Index(fields=['is_active', 'start_date'], name='myapp_hacka_is_acti_488e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='hackathonsubmission',
            index=models.Index(fields=['hackathon', 'submitted_at'], name='myapp_hacka_hackath_cd4a66_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['score'], name='myapp_leade_score_5f4dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['user', 'status'], name='myapp_learn_user_id_4d960b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningpath',
            index=models.Index(fields=['user', 'started_at'], name='myapp_learn_user_id_96ce43_idx'),
        ),
        migrations.AddIndex(
            model_name='modulecompletion',
            index=models.Index(fields=['user', 'content'], name='myapp_modul_user_id_72fe11_idx'),
        ),
        migrations.AddIndex(
            model_name='modulecontent',
            index=models.Index(fields=['module', 'order'], name='myapp_modul_module__36a5da_idx'),
        ),
        migrations.AddIndex(
            model_name='progressnode',
            index=models.Index(fields=['user', 'timestamp'], name='myapp_progr_user_id_3108d6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['competency', 'difficulty', 'is_active'], name='myapp_quest_compete_efd160_idx'),
        ),
        migrations.AddIndex(
            model_name='quizassessment',
            index=models.Index(fields=['user', 'created_at'], name='myapp_quiza_user_id_4f67e7_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'competency', 'start_time'], name='myapp_quiza_user_id_db6ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['status', 'start_time'], name='myapp_quiza_status_7dab96_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresponse',
            index=models.Index(fields=['quiz_attempt', 'is_correct'], name='myapp_quizr_quiz_at_b20af3_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompetency',
            index=models.Index(fields=['user', 'score'], name='myapp_userc_user_id_a2aeca_idx'),
        ),
    ]
