# Generated by Django 5.2.4 on 2025-07-25 08:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_answer_options_alter_competency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict)),
                ('comments', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackathonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('invite_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hackathon',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='hackathonsubmission',
            options={'ordering': ['-final_score', '-submitted_at']},
        ),
        migrations.RemoveIndex(
            model_name='hackathon',
            name='myapp_hacka_is_acti_488e3a_idx',
        ),
        migrations.RenameField(
            model_name='hackathonsubmission',
            old_name='score',
            new_name='final_score',
        ),
        migrations.RenameField(
            model_name='hackathonsubmission',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RemoveField(
            model_name='hackathonsubmission',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='hackathonsubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='allow_individual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='allow_student_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='evaluation_criteria',
            field=models.JSONField(default=dict, help_text='JSON object with criterion names and max scores'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 24, 8, 24, 52, 321099, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_start',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 25, 8, 25, 19, 397220, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('in_progress', 'In Progress'), ('evaluation', 'Under Evaluation'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='team_size_max',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='team_size_min',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='individual_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='prize_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='project_title',
            field=models.CharField(default='Untitled Project', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 25, 8, 26, 27, 663181, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='max_participants',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=models.Index(fields=['status', 'start_date'], name='myapp_hacka_status_a56383_idx'),
        ),
        migrations.AddIndex(
            model_name='hackathon',
            index=models.Index(fields=['is_active', 'registration_start'], name='myapp_hacka_is_acti_b297c6_idx'),
        ),
        migrations.AddField(
            model_name='hackathonevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonevaluation',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='myapp.hackathonsubmission'),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='myapp.hackathon'),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='myapp.hackathon'),
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='hackathon_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='myapp.hackathonteam'),
        ),
        migrations.AddField(
            model_name='hackathonsubmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myapp.hackathonteam'),
        ),
        migrations.AddIndex(
            model_name='hackathonsubmission',
            index=models.Index(fields=['hackathon', 'final_score'], name='myapp_hacka_hackath_eccd65_idx'),
        ),
        migrations.AddIndex(
            model_name='hackathonevaluation',
            index=models.Index(fields=['submission', 'evaluator'], name='myapp_hacka_submiss_8dc912_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hackathonevaluation',
            unique_together={('submission', 'evaluator')},
        ),
        migrations.AddIndex(
            model_name='hackathonteam',
            index=models.Index(fields=['hackathon', 'is_active'], name='myapp_hacka_hackath_06eced_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hackathonteam',
            unique_together={('hackathon', 'name')},
        ),
        migrations.AddIndex(
            model_name='hackathonregistration',
            index=models.Index(fields=['hackathon', 'is_active'], name='myapp_hacka_hackath_547945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hackathonregistration',
            unique_together={('hackathon', 'user')},
        ),
    ]
