# Generated by Django 5.1 on 2025-07-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_codingproblem_codesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecontent',
            name='quiz_file',
            field=models.FileField(blank=True, help_text='Upload CSV file for quiz questions.', null=True, upload_to='quiz_csvs/'),
        ),
    ]
