# Generated by Django 5.1 on 2025-07-26 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('selected_answer', models.CharField(max_length=255)),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='myapp.quizattemptlearningpath')),
            ],
            options={
                'indexes': [models.Index(fields=['quiz_attempt', 'question_index'], name='myapp_quizu_quiz_at_16fc8b_idx')],
                'unique_together': {('quiz_attempt', 'question_index')},
            },
        ),
    ]
