# Generated by Django 5.1 on 2025-07-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_quizuseranswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
