# Generated by Django 5.1 on 2025-07-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_delete_badge'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='learningpath',
            name='myapp_learn_user_id_4d960b_idx',
        ),
        migrations.RemoveIndex(
            model_name='learningpath',
            name='myapp_learn_user_id_96ce43_idx',
        ),
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together=set(),
        ),
    ]
