# Generated by Django 5.2.4 on 2025-07-28 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_customuser_is_verified_customuser_token_created_at_and_more'),
        ('myapp', '0022_fix_duplicate_emails'),
    ]

    operations = [
    ]
